### ISSUE TITLE
Window cannot be closed on title-screen

### ISSUE THREAD

**Issue by lmcnulty** [nevat/abbayedesmorts-gpl#11]
On Debian with x11, the standard ways of closing a window (eg. clicking on the X in the titlebar) do not cause the program to exit while the title-screen or the text introduction (beginning "13th Century") are on-screen. Pressing escape to quit works as expected. Once the game begins and Jean is controllable, then the window can be closed as expected.

**Comment by AMDmi3** [comment]
Should be easy - SDL_QUIT is not handled in startscreen.c, maybe some other event loops.

**Comment by carstene1ns** [comment]
Right, should be an easy fix.
