### ISSUE TITLE
Flathub submission

### ISSUE THREAD

**Issue by Rampoina** [nevat/abbayedesmorts-gpl#12]
Hello,

I've packaged and submitted your application to [flathub](https://github.com/flathub/flathub/pull/1212):
Please let us know if you want to own it.

Best regards,

**Comment by LeandroStanger** [comment]
https://flathub.org/apps/details/com.locomalito.abbayedesmorts

**Comment by nevat** [comment]
Thanks for package this program in to Flatpak.
