### ISSUE TITLE
Opens with black screen

### ISSUE THREAD

**Issue by bufalo1973** [nevat/abbayedesmorts-gpl#18]
System: KDE Neon 22.04 64 bits on a i3 laptop.

I've cloned and compiled without touching anything.
Compiling is flawless but when I run it it only shows a black screen. I can turn from and to full screen but nothing else. Sometimes it just throws a segmentation fault but that's it.

All the assets are in their place.

**Comment by carstene1ns** [comment]
Did you pass `DATADIR="."` while compiling? Default is a full installation, so assets are expected in `/usr/share...`.

However, we should likely show an error message, when there are no assets found. Will add this.
