### ISSUE TITLE
Graphics glitches with images that are constructed from several tiles

### ISSUE THREAD

**Issue by th-otto** [nevat/abbayedesmorts-gpl#20]
In the SDL2 version, some graphics that are constructed have one line of background between the upper and lower part, like the bell:

![sdl2](https://github.com/user-attachments/assets/f845b18c-50f4-459d-a201-8b6c380a4073)

The older SDL 1.2 version does not have this problem:

![sdl12](https://github.com/user-attachments/assets/85e6515e-583f-443b-a502-e797a6955890)

**Comment by carstene1ns** [comment]
These are scaling artifacts. If you disable linear scaling in `main.c` line 47, these are not present.

**Comment by th-otto** [comment]
Ok, but why is it then enabled by default?

**Comment by vanfanel** [comment]
> Ok, but why is it then enabled by default?

Bilinear scaling looks way better than nearest, unless you pair nearest with integer scaling.

**Comment by carstene1ns** [comment]
I have worked around this in the new version.
