### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by AMDmi3** [nevat/abbayedesmorts-gpl#3]
Could you please tag latest trunk as a new release? It will make packaging easier, as master branch contains crucial fixes after the latest tag.

**Comment by AMDmi3** [comment]
Cast @carstene1ns

**Comment by carstene1ns** [comment]
Yeah, you are right, will push a bugfix release (2.0.1) in a bit.
I have some old polishing for the README locally, which I need to cleanup and commit first, but hope to have that ready by the end of  the week.

**Comment by carstene1ns** [comment]
done: https://github.com/nevat/abbayedesmorts-gpl/releases/tag/v2.0.1

**Comment by AMDmi3** [comment]
Thank you!
