### ISSUE TITLE
Install the supplied AppData file

### ISSUE THREAD

**Issue by musuruan** [nevat/abbayedesmorts-gpl#5]
Please consider installing this AppData file I wrote: 
https://musuruan.fedorapeople.org/abbaye.appdata.xml

This is used in GNOME and KDE software installers to add the application description and some screenshots. We'd love to showcase more applications, but without the extra data file we can't. The AppData file needs to be installed to /usr/share/appdata/ on Linux and the basename needs to match the .desktop basename. It would also be great if you could integrate the file with your translation system (e.g. intltool) to make the descriptions translated.

See https://www.freedesktop.org/software/appstream/docs/index.html for more details. 

Thanks!

**Comment by musuruan** [comment]
New AppData file location:
http://pkgs.fedoraproject.org/cgit/rpms/abbayedesmorts-gpl.git/plain/abbaye.appdata.xml

**Comment by nevat** [comment]
Hi,

AppData file added to the repo.

Thanks for your time !
