### ISSUE TITLE
Support LDFLAGS

### ISSUE THREAD

**Issue by musuruan** [nevat/abbayedesmorts-gpl#9]
During the Fedora package review, I made the following patch to support LDFLAGS.

http://pkgs.fedoraproject.org/cgit/rpms/abbayedesmorts-gpl.git/plain/abbayedesmorts-gpl-2.0.1-ldflags.patch

I hope you can merge it.

**Comment by nevat** [comment]
Hi musuruan,

Thanks for your patch (and your time!), I will test ASAP.

**Comment by nevat** [comment]
Patch applied. Thanks for your code !
